# Generated by Django 4.0.1 on 2022-02-05 13:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/default.jpg', upload_to=users.models.user_image_upload_to),
        ),
    ]
