# Generated by Django 4.0.1 on 2022-02-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
