# Generated by Django 4.0.1 on 2022-02-05 13:03

import camps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_rename_body_camp_main_body_camp_position_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(default='camps/default.jpg', upload_to=camps.models.camp_image_upload_to),
        ),
    ]
